name: golangci-lint
on:
  pull_request:
   paths-ignore:
      - 'README.md'
      - '*_test.go'
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.22.x]
        # os: [ubuntu-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63

          # Optional: golangci-lint command line arguments.
          args: --timeout=5m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
