name: golangci-lint
on:
  pull_request:
   paths-ignore:
      - 'README.md'
      - '*_test.go'
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.18.x]
        # os: [ubuntu-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          # version: v1.45
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --timeout=5m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
